services:
  ssh-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ssh-service
    restart: unless-stopped
    environment:
      SSH_DB_HOST: ssh-db
      SSH_DB_USER: ${MYSQL_USER}
      SSH_DB_PASSWORD: ${MYSQL_PASSWORD}
      SSH_DB_NAME: ${MYSQL_DATABASE}
    ports:
      - "8085:8080"
    depends_on:
      - ssh-db
      - ssh-password-db
    env_file:
      - .env

  ssh-db:
    image: mysql:latest
    container_name: ssh-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ssh-db-data:/var/lib/mysql
    env_file:
      - .env

  ssh-password-db:  
    image: mysql:latest
    container_name: ssh-password-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_PASSWORD_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - ssh-password-db-data:/var/lib/mysql
    env_file:
      - .env

volumes:
  ssh-db-data:
  ssh-password-db-data:
