version: "3.8"

services:
  ssh-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    restart: unless-stopped
    environment:
      AUTH_DB_HOST: auth-db
      AUTH_DB_USER: ${MYSQL_USER}
      AUTH_DB_PASSWORD: ${MYSQL_PASSWORD}
      AUTh_DB_NAME: ${MYSQL_DATABASE}
    ports:
      - "8085:8080"
    depends_on:
      - auth-db
      - auth-password-db
    env_file:
      - .env

  auth-db:
    image: mysql:latest
    container_name: auth-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - auth-db-data:/var/lib/mysql
    env_file:
      - .env

  auth-password-db:
    image: mysql:latest
    container_name: auth-password-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_PASSWORD_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - auth-password-db-data:/var/lib/mysql
    env_file:
      - .env

volumes:
  auth-db-data:
  auth-password-db-data:
