name: Go CI

on:
  push:
    branches:
      - dev
    paths:
      - '**.go'  
      - 'go.mod'
      - 'go.sum'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: cd into backend dir 
        run: cd ~/backend
        
      - name: Install Dependencies
        run: go mod tidy

      - name: Build Project
        run: go build -v ./...

      #- name: Run Tests
        #run: go test -v ./...
