name: Go CI/CD

on:
  push:
    branches:
      - dev
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Install Dependencies
        run: go mod tidy
        working-directory: backend

      - name: Build Project
        run: go build -v ./...
        working-directory: backend

  create_pr:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      pr_number: ${{ steps.create-pr.outputs.pr_number }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.TALFAZA_TOKEN }}
          base: main
          branch: dev
          title: "Auto PR from dev to main"
          body: "This PR was automatically created to merge dev into main."
          labels: "auto-merge"
          draft: false

      - name: Debug PR Creation
        run: |
          if [ -z "${{ steps.create-pr.outputs.pr_number }}" ]; then
            echo "::warning::No PR created - likely no changes detected"
          else
            echo "Created PR #${{ steps.create-pr.outputs.pr_number }}"
          fi

  auto_merge:
    needs: [create_pr]
    runs-on: ubuntu-latest
    steps:
      - name: Enable Auto-Merge
        if: ${{ needs.create_pr.outputs.pr_number }}
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.TALFAZA_TOKEN }}
          pull-request-number: ${{ needs.create_pr.outputs.pr_number }}
          merge-method: squash
          repository: Talfaza/Netfixer
